"use strict";

const { Yacht } = require("../models");
const bcrypt = require("bcryptjs");

let options = {};
if (process.env.NODE_ENV === "production") {
  options.schema = process.env.SCHEMA; 
}

module.exports = {
  async up(queryInterface, Sequelize) {
    await Yacht.bulkCreate(
      [
        {
          ownerId: 1,
          address: "300 Alton rd",
          city: "Miami",
          state: "FL",
          country: "USA",
          lat: 25.7716,
          lng: -80.1397,
          name: "Miami Mistress",
          description: "This Yacht is a perfect getaway, enjoy complimentary mixers, water and ice. Yacht equipped with floating water toys.",
          price4: 250,
          price6: 300,
          price8: 350,
          length: 53,
          builder: "Builder A",
          guests: 12,
          cabins: 3,
          speed: 25,
          bathrooms: 2,
          year: 2006,
        },
        {
          ownerId: 2,
          address: "La pier 2",
          city: "Monaco",
          state: "Monaco",
          country: "France",
          lat: 43.7333, // Assuming latitude for Monaco
          lng: 7.4167, // Assuming longitude for Monaco
          name: "WavesKing",
          description: "Stylish Yacht with 2 cabins and room for 2 crew members.",
          price4: 343,
          price6: 400,
          price8: 450,
          length: 63,
          builder: "Builder B",
          guests: 10,
          cabins: 4,
          speed: 30,
          bathrooms: 3,
          year: 2018,
        },
        {
          ownerId: 1,
          address: "4441 Collins ave",
          city: "Miami Beach",
          state: "FL",
          country: "USA",
          lat: 25.8174, // Assuming latitude for Miami Beach
          lng: -80.1229, // Assuming longitude for Miami Beach
          name: "Ocean12",
          description: "Ocean12 is a great choice for any occasion, bring your friends together and enjoy the ocean in this stylish yacht.",
          price4: 133,
          price6: 180,
          price8: 220,
          length: 71,
          builder: "Builder C",
          guests: 15,
          cabins: 5,
          speed: 35,
          bathrooms: 4,
          year: 2019,
        },
        {
          ownerId: 1,
          address: "909 Marina Rd",
          city: "Dubai",
          state: "Dubai",
          country: "UAE",
          lat: 25.276987,
          lng: 55.296249,
          name: "Dubai Dhow",
          description: "Experience the opulence of Dubai from the sea.",
          price4: 650,
          price6: 750,
          price8: 850,
          length: 90,
          builder: "Builder L",
          guests: 18,
          cabins: 6,
          speed: 45,
          bathrooms: 6,
          year: 2021,
        },
        {
          ownerId: 1,
          address: "1010 Marina Blvd",
          city: "Dubrovnik",
          state: "Dubrovnik-Neretva",
          country: "Croatia",
          lat: 42.6507,
          lng: 18.0944,
          name: "Adriatic Star",
          description: "Explore the Adriatic Sea from Dubrovnik.",
          price4: 440,
          price6: 540,
          price8: 640,
          length: 74,
          builder: "Builder M",
          guests: 13,
          cabins: 5,
          speed: 36,
          bathrooms: 4,
          year: 2020,
        },
        {
          ownerId: 1,
          address: "101 Marina Way",
          city: "Athens",
          state: "Attica",
          country: "Greece",
          lat: 37.9838,
          lng: 23.7275,
          name: "Athenian Odyssey",
          description: "Explore the ancient ruins from the sea.",
          price4: 450,
          price6: 550,
          price8: 650,
          length: 78,
          builder: "Builder D",
          guests: 16,
          cabins: 6,
          speed: 38,
          bathrooms: 5,
          year: 2021,
        },
        {
          ownerId: 1,
          address: "202 Marina Rd",
          city: "Barcelona",
          state: "Catalonia",
          country: "Spain",
          lat: 41.3851,
          lng: 2.1734,
          name: "Catalonian Cruiser",
          description: "Enjoy the vibrant culture of Barcelona.",
          price4: 480,
          price6: 580,
          price8: 680,
          length: 76,
          builder: "Builder E",
          guests: 14,
          cabins: 5,
          speed: 36,
          bathrooms: 5,
          year: 2017,
        },
        {
          ownerId: 1,
          address: "303 Marina St",
          city: "Bodrum",
          state: "Muğla",
          country: "Turkey",
          lat: 37.0344,
          lng: 27.4305,
          name: "Turkish Delight",
          description: "Cruise the beautiful Turkish coastline.",
          price4: 470,
          price6: 570,
          price8: 670,
          length: 80,
          builder: "Builder F",
          guests: 13,
          cabins: 5,
          speed: 39,
          bathrooms: 5,
          year: 2016,
        },
        {
          ownerId: 1,
          address: "404 Marina Ave",
          city: "British Virgin Islands",
          state: "British Virgin Islands",
          country: "UK",
          lat: 18.4207,
          lng: -64.6399,
          name: "Island Hopper",
          description: "Explore the paradise of the British Virgin Islands.",
          price4: 510,
          price6: 610,
          price8: 710,
          length: 82,
          builder: "Builder G",
          guests: 15,
          cabins: 6,
          speed: 40,
          bathrooms: 6,
          year: 2015,
        },
        {
          ownerId: 1,
          address: "505 Marina Ln",
          city: "Cancun",
          state: "Quintana Roo",
          country: "Mexico",
          lat: 21.1619,
          lng: -86.8515,
          name: "Caribbean Breeze",
          description: "Enjoy the vibrant waters of Cancun.",
          price4: 520,
          price6: 620,
          price8: 720,
          length: 79,
          builder: "Builder H",
          guests: 14,
          cabins: 5,
          speed: 37,
          bathrooms: 5,
          year: 2022,
        },
        {
          ownerId: 1,
          address: "606 Marina Dr",
          city: "Cartagena",
          state: "Bolívar",
          country: "Colombia",
          lat: 10.3910,
          lng: -75.4794,
          name: "Colombian Charm",
          description: "Sail the historic waters of Cartagena.",
          price4: 430,
          price6: 530,
          price8: 630,
          length: 75,
          builder: "Builder I",
          guests: 13,
          cabins: 4,
          speed: 36,
          bathrooms: 4,
          year: 2018,
        },
        {
          ownerId: 1,
          address: "707 Marina Blvd",
          city: "Casa De Campo",
          state: "La Romana",
          country: "Dominican Republic",
          lat: 18.4206,
          lng: -68.9118,
          name: "Dominican Dream",
          description: "Relax in the luxury of Casa De Campo.",
          price4: 460,
          price6: 560,
          price8: 660,
          length: 81,
          builder: "Builder J",
          guests: 16,
          cabins: 5,
          speed: 38,
          bathrooms: 5,
          year: 2017,
        },
       
     
      ],
      { validate: true }
    );
  },

  async down(queryInterface, Sequelize) {
    options.tableName = "Yachts";

    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(options, {
      ownerId: { [Op.in]: ["1", "2"] },
    });
    ///...
  },
};
